package com.mrinabh.scrabble;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * I am not going to spend time documenting this class since it was generated by
 * Eclipse STS. But if you have questions, happy to answer them/take them
 * offline
 * 
 * @author mrinabh
 *
 */
@SpringBootApplication
public class ScrabbleSolverServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(ScrabbleSolverServiceApplication.class, args);
    }

}
